# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InputCords.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InputCords(object):
    def setupUi(self, InputCords):
        InputCords.setObjectName("InputCords")
        InputCords.setFixedSize(400, 300)

        self.background = QtWidgets.QLabel(InputCords)
        self.background.setGeometry(0, 0, 400, 300)  # Задаем размер на всю форму
        self.background.setPixmap(

            QtGui.QPixmap("error_photo.jpg").scaled(400, 300, QtCore.Qt.KeepAspectRatioByExpanding,
                                                    QtCore.Qt.SmoothTransformation))
        self.background.setObjectName("background")
        self.overlay = QtWidgets.QLabel(InputCords)
        self.overlay.setGeometry(0, 0, 400, 300)
        self.overlay.setStyleSheet("background-color: rgba(230, 230, 230, 230);")  # Черный полупрозрачный слой
        self.overlay.setObjectName("overlay")

        font = QtGui.QFont()
        font.setPointSize(8)
        InputCords.setFont(font)
        self.label = QtWidgets.QLabel(InputCords)
        self.label.setGeometry(QtCore.QRect(100, 10, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.first_input = QtWidgets.QLabel(InputCords)
        self.first_input.setGeometry(QtCore.QRect(20, 70, 21, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.first_input.setFont(font)
        self.first_input.setObjectName("first_input")
        self.second_input = QtWidgets.QLabel(InputCords)
        self.second_input.setGeometry(QtCore.QRect(20, 120, 21, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.second_input.setFont(font)
        self.second_input.setObjectName("second_input")
        self.first_input_2 = QtWidgets.QLabel(InputCords)
        self.first_input_2.setGeometry(QtCore.QRect(20, 170, 21, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.first_input_2.setFont(font)
        self.first_input_2.setObjectName("first_input_2")
        self.pushButton = QtWidgets.QPushButton(InputCords)
        self.pushButton.setGeometry(QtCore.QRect(260, 240, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(InputCords)
        self.lineEdit.setGeometry(QtCore.QRect(60, 80, 191, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(InputCords)
        self.lineEdit_2.setGeometry(QtCore.QRect(60, 130, 191, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.about_rad_1 = QtWidgets.QLabel(InputCords)
        self.about_rad_1.setGeometry(QtCore.QRect(260, 130, 191, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.about_rad_1.setFont(font)
        self.about_rad_1.setObjectName("about_rad_1")

        self.lineEdit_3 = QtWidgets.QLineEdit(InputCords)
        self.lineEdit_3.setGeometry(QtCore.QRect(60, 180, 191, 22))
        self.lineEdit_3.setObjectName("lineEdit_3")

        self.about_rad_2 = QtWidgets.QLabel(InputCords)
        self.about_rad_2.setGeometry(QtCore.QRect(260, 180, 191, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.about_rad_2.setFont(font)
        self.about_rad_2.setObjectName("about_rad_2")

        self.retranslateUi(InputCords)
        QtCore.QMetaObject.connectSlotsByName(InputCords)

    def retranslateUi(self, InputCords):
        _translate = QtCore.QCoreApplication.translate
        InputCords.setWindowTitle(_translate("InputCords", "Dialog"))
        self.label.setText(_translate("InputCords", "Введите координаты"))
        self.pushButton.setText(_translate("InputCords", "Перевести"))
        # self.about_rad_1.setText(_translate("InputCords", "в радианах"))
        # self.about_rad_2.setText(_translate("InputCords", "в радианах"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QDialog()
    ui = Ui_InputCords()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
